---
- name: Fetch Secrets
  hosts: all
  tasks:
    - name: Database Password
      connection: local
      azure.azcollection.azure_rm_keyvaultsecret_info:
        vault_uri: "https://nextcloud-secrets.vault.azure.net/"
        name: db-password
      register: db_password
